%bcond_without tests
%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/jazzy/.*$
%global __requires_exclude_from ^/opt/ros/jazzy/.*$

Name:           ros-jazzy-mola-relocalization
Version:        2.2.1
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS mola_relocalization package

License:        GPLv3
URL:            https://github.com/MOLAorg/mola/tree/develop/mola_relocalization
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-jazzy-mola-common
Requires:       ros-jazzy-mola-pose-list
Requires:       ros-jazzy-mp2p-icp
Requires:       ros-jazzy-mrpt-libmaps
Requires:       ros-jazzy-mrpt-libobs
Requires:       ros-jazzy-mrpt-libslam
Requires:       ros-jazzy-ros-workspace
BuildRequires:  cmake3
BuildRequires:  ros-jazzy-mola-common
BuildRequires:  ros-jazzy-mola-pose-list
BuildRequires:  ros-jazzy-mp2p-icp
BuildRequires:  ros-jazzy-mrpt-libmaps
BuildRequires:  ros-jazzy-mrpt-libobs
BuildRequires:  ros-jazzy-mrpt-libslam
BuildRequires:  ros-jazzy-ros-workspace
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%if 0%{?with_tests}
BuildRequires:  ros-jazzy-mola-test-datasets
%endif

%description
C++ library with algorithms for relocalization, global localization, or pose
estimation given a large initial uncertainty

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jazzy/setup.sh" ]; then . "/opt/ros/jazzy/setup.sh"; fi
mkdir -p .obj-%{_target_platform} && cd .obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/jazzy" \
    -DCMAKE_PREFIX_PATH="/opt/ros/jazzy" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
%if !0%{?with_tests}
    -DBUILD_TESTING=OFF \
%endif
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jazzy/setup.sh" ]; then . "/opt/ros/jazzy/setup.sh"; fi
%make_install -C .obj-%{_target_platform}

%if 0%{?with_tests}
%check
# Look for a Makefile target with a name indicating that it runs tests
TEST_TARGET=$(%__make -qp -C .obj-%{_target_platform} | sed "s/^\(test\|check\):.*/\\1/;t f;d;:f;q0")
if [ -n "$TEST_TARGET" ]; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jazzy/setup.sh" ]; then . "/opt/ros/jazzy/setup.sh"; fi
CTEST_OUTPUT_ON_FAILURE=1 \
    %make_build -C .obj-%{_target_platform} $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif

%files
%license LICENSE
/opt/ros/jazzy

%changelog
* Sat Nov 08 2025 Jose-Luis Blanco-Claraco <joseluisblancoc@gmail.com> - 2.2.1-1
- Autogenerated by Bloom

* Tue Oct 28 2025 Jose-Luis Blanco-Claraco <joseluisblancoc@gmail.com> - 2.2.0-1
- Autogenerated by Bloom

* Mon Oct 20 2025 Jose-Luis Blanco-Claraco <joseluisblancoc@gmail.com> - 2.1.0-1
- Autogenerated by Bloom

* Mon Oct 13 2025 Jose-Luis Blanco-Claraco <joseluisblancoc@gmail.com> - 2.0.0-1
- Autogenerated by Bloom

* Fri Jun 06 2025 Jose-Luis Blanco-Claraco <joseluisblancoc@gmail.com> - 1.9.0-1
- Autogenerated by Bloom

* Sun May 25 2025 Jose-Luis Blanco-Claraco <joseluisblancoc@gmail.com> - 1.8.0-1
- Autogenerated by Bloom

* Tue May 06 2025 Jose-Luis Blanco-Claraco <joseluisblancoc@gmail.com> - 1.7.0-1
- Autogenerated by Bloom

* Wed Apr 23 2025 Jose-Luis Blanco-Claraco <joseluisblancoc@gmail.com> - 1.6.4-1
- Autogenerated by Bloom

* Sat Mar 15 2025 Jose-Luis Blanco-Claraco <joseluisblancoc@gmail.com> - 1.6.3-1
- Autogenerated by Bloom

* Sat Feb 22 2025 Jose-Luis Blanco-Claraco <joseluisblancoc@gmail.com> - 1.6.2-1
- Autogenerated by Bloom

* Thu Feb 13 2025 Jose-Luis Blanco-Claraco <joseluisblancoc@gmail.com> - 1.6.1-1
- Autogenerated by Bloom

* Tue Jan 21 2025 Jose-Luis Blanco-Claraco <joseluisblancoc@gmail.com> - 1.6.0-1
- Autogenerated by Bloom

* Sun Dec 29 2024 Jose-Luis Blanco-Claraco <joseluisblancoc@gmail.com> - 1.5.1-1
- Autogenerated by Bloom

* Thu Dec 26 2024 Jose-Luis Blanco-Claraco <joseluisblancoc@gmail.com> - 1.5.0-1
- Autogenerated by Bloom

* Fri Dec 20 2024 Jose-Luis Blanco-Claraco <joseluisblancoc@gmail.com> - 1.4.1-1
- Autogenerated by Bloom

* Wed Dec 18 2024 Jose-Luis Blanco-Claraco <joseluisblancoc@gmail.com> - 1.4.0-1
- Autogenerated by Bloom

* Wed Dec 11 2024 Jose-Luis Blanco-Claraco <joseluisblancoc@gmail.com> - 1.3.0-1
- Autogenerated by Bloom

* Sun Sep 29 2024 Jose-Luis Blanco-Claraco <joseluisblancoc@gmail.com> - 1.2.1-1
- Autogenerated by Bloom

* Mon Sep 16 2024 Jose-Luis Blanco-Claraco <joseluisblancoc@gmail.com> - 1.2.0-1
- Autogenerated by Bloom

* Wed Aug 28 2024 Jose-Luis Blanco-Claraco <joseluisblancoc@gmail.com> - 1.1.3-1
- Autogenerated by Bloom

* Sun Aug 18 2024 Jose-Luis Blanco-Claraco <joseluisblancoc@gmail.com> - 1.1.0-1
- Autogenerated by Bloom

* Mon Jul 29 2024 Jose-Luis Blanco-Claraco <joseluisblancoc@gmail.com> - 1.0.8-1
- Autogenerated by Bloom

* Wed Jul 24 2024 Jose-Luis Blanco-Claraco <joseluisblancoc@gmail.com> - 1.0.7-1
- Autogenerated by Bloom

* Fri Jun 21 2024 Jose-Luis Blanco-Claraco <joseluisblancoc@gmail.com> - 1.0.6-1
- Autogenerated by Bloom

* Tue May 28 2024 Jose-Luis Blanco-Claraco <joseluisblancoc@gmail.com> - 1.0.5-1
- Autogenerated by Bloom

* Thu Apr 18 2024 Jose-Luis Blanco-Claraco <joseluisblancoc@gmail.com> - 1.0.2-2
- Autogenerated by Bloom

* Thu Apr 04 2024 Jose-Luis Blanco-Claraco <joseluisblancoc@gmail.com> - 1.0.2-1
- Autogenerated by Bloom

